spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vkkart
    username: root
    password: welcome123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
